=== FranciscoRosa11/PRI2020/TPC2/project-record.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="project-record">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="meta"/>
        <xs:element ref="abstract"/>
        <xs:element ref="workteam"/>
        <xs:element minOccurs="0" ref="logs"/>
        <xs:element ref="deliverables"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element minOccurs="0" ref="subtitle"/>
        <xs:element ref="key-name"/>
        <xs:element ref="supervisors"/>
        <xs:element ref="begin-date"/>
        <xs:element ref="end-date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="key-name" type="xs:string"/>
  <xs:element name="supervisors" type="supervisor"/>
  <xs:complexType name="supervisor">
    <xs:sequence>
      <xs:element ref="supervisor"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="supervisor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element minOccurs="0" ref="email"/>
        <xs:element minOccurs="0" ref="homepage"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="homepage" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="begin-date" type="xs:string"/>
  <xs:element name="end-date" type="xs:string"/>
  <xs:element name="abstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--  elemento paragrafo b = bold i = italico etc etc -->
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="i"/>
        <xs:element ref="u"/>
        <xs:element ref="ackron"/>
        <xs:element ref="xref"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="u"/>
        <xs:element ref="ackron"/>
        <xs:element ref="xref"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="u"/>
        <xs:element ref="ackron"/>
        <xs:element ref="xref"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="i"/>
        <xs:element ref="ackron"/>
        <xs:element ref="xref"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="ackron" type="xs:string"/>
  <xs:element name="xref">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.xref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.xref">
    <xs:attribute name="url" use="required"/>
  </xs:attributeGroup>
  <xs:element name="workteam" type="student"/>
  <xs:complexType name="student">
    <xs:sequence>
      <xs:element ref="student"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ident"/>
        <xs:element ref="name"/>
        <xs:element ref="email"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ident" type="xs:string"/>
  <xs:element name="logs">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="log"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="log">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="date"/>
        <xs:element ref="description"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="date" type="xs:string"/>
  <xs:element name="description">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deliverables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="xref"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FranciscoRosa11/PRI2020/TPC2/project-record1.xml
<?xml version="1.0" encoding="UTF-8"?>
<project-record xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/franc/Desktop/PLC/PRI/TPC2/project-record.xsd">
    <meta>
        <title>Schema e Stylesheet para tratamento de teses em XML</title>
        <key-name>PED_MICEI2002_TESES</key-name>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
            </supervisor>
        </supervisors>
        <begin-date>Outubro 2020</begin-date>
        <end-date>Outubro 2020</end-date>
    </meta>
    <abstract>
        <p>
        O XML, validado pelo schema, juntamente com o potente processamento via XSLT, permite dispor de facilidades acrescidas no tratamento de informação de uma forma standard e partilhável. Estas são, além de outras evidentes vantagens, as que abrem caminho a uma mais que provável evolução desta tecnologia nos círculos comerciais e de investigação. Outro facto importante, diz respeito à substituição de interfaces EDI por XML em aplicações bussiness oriented.
        
        O trabalho apresentado contempla um schema, uma stylesheet, e a instância do schema em XML. A instância é o próprio relatório.
        
        O trabalho pretende definir uma estrutura expedita e funcional, passível de ser aplicada a um trabalho descritivo, como por exemplo uma tese. Não é objectivo do trabalho criar uma implementação sistemática de todos os objectos possíveis, mas sim criar algumas utilizações mais comuns para exemplificar a potência destas linguagens.
        Ficam neste trabalho em aberto algumas ideias, a serem aplicadas mais tarde a quando da escrita da tese, ou pré-tese, porque na verdade o facto de manter o documento num formato exportável para vários formatos, para várias plataformas, e anotado, garante qualquer tratamento no futuro, constituindo uma vantagem muito importante a ter em conta.
        </p>
    </abstract>
    <workteam>
        <student>
            <ident>80749</ident>
            <name>Francisco Braga Urbano Rosa</name>
            <email>a80749@alunos.uminho.pt</email>
        </student>
    </workteam>
    <deliverables>
        <xref url="file:/C:/Users/franc/Desktop/PLC/PRI/TPC2/project-record.xsd">
        </xref>
        <xref url="file:/C:/Users/franc/Desktop/PLC/PRI/TPC2/project-record1.xml">
        </xref>
        <xref url="file:/C:/Users/franc/Desktop/PLC/PRI/TPC2/project-record.dtd">
        </xref>
    </deliverables>
</project-record>
